project_id = "waczgosbsrorcibwfayv"

[functions.check-payment-status]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false
