name: spartan_app
description: A new Flutter project.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  supabase_flutter: ^2.12.0
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  http: ^1.1.0
  package_info_plus: ^8.0.0
  intl: any
  mask_text_input_formatter: ^2.9.0
  image_picker: ^1.0.4
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  app_links: ^6.3.2
  flutter_image_compress: ^2.3.0
  shared_preferences: ^2.2.2
  windows_single_instance: any
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.2
  universal_html: ^2.3.0
  file_picker: ^10.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.3
  image: ^4.8.0

flutter_launcher_icons:
  android: false
  ios: false
  image_path: "web/icons/Icon-512.png"
  windows:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
